from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

from backend.app.account_sources.mappers import build_seed_post_from_fixture_item
from backend.app.domain.post_models import SinglePostInsights
from backend.app.services.account_analysis_jobs import enqueue_account_analysis_job
from backend.app.services.post_insights_service import build_single_post_insights


def _build_seed_post(
    fixture_item: dict[str, object],
    account_id: str,
) -> SinglePostInsights:
    return build_seed_post_from_fixture_item(fixture_item, account_id=account_id)


async def _analyze_posts(
    posts: list[SinglePostInsights],
    concurrency: int,
) -> list[SinglePostInsights]:
    semaphore = asyncio.Semaphore(max(1, min(concurrency, 3)))

    async def _run_one(index: int, post: SinglePostInsights) -> SinglePostInsights | None:
        async with semaphore:
            try:
                history = [candidate for i, candidate in enumerate(posts) if i != index]
                response = await build_single_post_insights(
                    target_post=post,
                    historical_posts=history,
                    run_ai=True,
                )
                return response["post"]
            except Exception as exc:
                print(f"Skipping post {post.media_id}: {exc}")
                return None

    tasks = [asyncio.create_task(_run_one(index, post)) for index, post in enumerate(posts)]
    analyzed = await asyncio.gather(*tasks)
    return [post for post in analyzed if post is not None]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Enqueue account analysis job from fixture JSON.")
    parser.add_argument("--fixture", required=True, help="Path to fixture JSON generated by generate_ig_raw_fixtures.")
    parser.add_argument("--account-id", default=None, help="Optional override for account_id.")
    parser.add_argument("--concurrency", type=int, default=3, help="Max concurrent post analyses (hard-capped at 3).")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    fixture_path = Path(args.fixture)
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))

    items = fixture.get("items")
    if not isinstance(items, list) or not items:
        raise ValueError("Fixture must contain a non-empty 'items' list.")

    raw_account_id = args.account_id or fixture.get("username") or "fixture_account"
    account_id = str(raw_account_id).strip()
    seed_posts = [_build_seed_post(item, account_id=account_id) for item in items]
    analyzed_posts = asyncio.run(_analyze_posts(seed_posts, concurrency=args.concurrency))

    if not analyzed_posts:
        raise RuntimeError("No posts were analyzed successfully; nothing to enqueue.")

    payload = {
        "account_id": account_id,
        "username": fixture.get("username"),
        "bio": fixture.get("biography") or fixture.get("bio"),
        "follower_count": fixture.get("followers_count") or fixture.get("follower_count"),
        "post_limit": min(len(analyzed_posts), 30),
        "posts": [post.model_dump(mode="python") for post in analyzed_posts],
    }
    queued = enqueue_account_analysis_job(payload)
    print(queued["job_id"])


if __name__ == "__main__":
    main()
