from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path
from typing import Any

from backend.app.domain.post_models import BenchmarkMetrics, CoreMetrics, DerivedMetrics, SinglePostInsights
from backend.app.services.account_analysis_jobs import enqueue_account_analysis_job
from backend.app.services.post_insights_service import build_single_post_insights
from backend.app.tools.fixture_to_creator_input import build_creator_post_ai_input_from_fixture


def _safe_int_or_none(value: Any) -> int | None:
    try:
        if value is None or (isinstance(value, str) and not value.strip()):
            return None
        return int(value)
    except (TypeError, ValueError):
        return None


def _build_seed_post(
    fixture_item: dict[str, Any],
    account_id: str,
) -> SinglePostInsights:
    creator_post = build_creator_post_ai_input_from_fixture(fixture_item)
    media_type = creator_post.post_type
    view_count = _safe_int_or_none(fixture_item.get("view_count"))
    like_count = _safe_int_or_none(fixture_item.get("like_count"))
    comment_count = _safe_int_or_none(fixture_item.get("comment_count"))

    core_metrics = CoreMetrics(
        reach=view_count,
        impressions=view_count,
        likes=like_count,
        comments=comment_count,
        shares=None,
        saves=None,
        profile_visits=None,
        website_taps=None,
        source_engagement_rate=None,
    )

    return SinglePostInsights(
        account_id=account_id,
        media_id=creator_post.post_id,
        media_url=creator_post.media_url or None,
        media_type=media_type,
        caption_text=creator_post.caption_text,
        post_category=None,
        creator_dominant_category=None,
        extracted_brand_mentions=[],
        safety_extra_flags={},
        follower_count=_safe_int_or_none(fixture_item.get("follower_count")),
        published_at=creator_post.posted_at,
        core_metrics=core_metrics,
        derived_metrics=DerivedMetrics(),
        benchmark_metrics=BenchmarkMetrics(),
    )


async def _analyze_posts(
    posts: list[SinglePostInsights],
    concurrency: int,
) -> list[SinglePostInsights]:
    semaphore = asyncio.Semaphore(max(1, min(concurrency, 3)))

    async def _run_one(index: int, post: SinglePostInsights) -> SinglePostInsights | None:
        async with semaphore:
            try:
                history = [candidate for i, candidate in enumerate(posts) if i != index]
                response = await build_single_post_insights(
                    target_post=post,
                    historical_posts=history,
                    run_ai=True,
                )
                return response["post"]
            except Exception as exc:
                print(f"Skipping post {post.media_id}: {exc}")
                return None

    tasks = [asyncio.create_task(_run_one(index, post)) for index, post in enumerate(posts)]
    analyzed = await asyncio.gather(*tasks)
    return [post for post in analyzed if post is not None]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Enqueue account analysis job from fixture JSON.")
    parser.add_argument("--fixture", required=True, help="Path to fixture JSON generated by generate_ig_raw_fixtures.")
    parser.add_argument("--account-id", default=None, help="Optional override for account_id.")
    parser.add_argument("--concurrency", type=int, default=3, help="Max concurrent post analyses (hard-capped at 3).")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    fixture_path = Path(args.fixture)
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))

    items = fixture.get("items")
    if not isinstance(items, list) or not items:
        raise ValueError("Fixture must contain a non-empty 'items' list.")

    account_id = (args.account_id or fixture.get("username") or "fixture_account").strip()
    seed_posts = [_build_seed_post(item, account_id=account_id) for item in items]
    analyzed_posts = asyncio.run(_analyze_posts(seed_posts, concurrency=args.concurrency))

    if not analyzed_posts:
        raise RuntimeError("No posts were analyzed successfully; nothing to enqueue.")

    payload = {
        "account_id": account_id,
        "post_limit": min(len(analyzed_posts), 30),
        "posts": [post.model_dump(mode="python") for post in analyzed_posts],
    }
    queued = enqueue_account_analysis_job(payload)
    print(queued["job_id"])


if __name__ == "__main__":
    main()
