"""Canonical domain models for Single Post Insights."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator


# -----------------------------
# Core metrics
# -----------------------------


class CoreMetrics(BaseModel):
    """Raw Instagram metrics captured from the source system for a single post."""

    model_config = ConfigDict(extra="forbid")

    reach: int | None = Field(default=None, description="Unique accounts reached by the post.")
    impressions: int | None = Field(default=None, description="Total impressions generated by the post.")
    likes: int | None = Field(default=None, description="Total likes on the post.")
    comments: int | None = Field(default=None, description="Total comments on the post.")
    shares: int | None = Field(default=None, description="Total shares of the post.")
    saves: int | None = Field(default=None, description="Total saves/bookmarks on the post.")
    profile_visits: int | None = Field(default=None, description="Profile visits attributed to the post.")
    website_taps: int | None = Field(default=None, description="Website taps attributed to the post.")
    source_engagement_rate: float | None = Field(
        default=None,
        description="Top-level raw engagement rate provided by source systems.",
    )


# -----------------------------
# Derived metrics
# -----------------------------


class DerivedMetrics(BaseModel):
    """Deterministic rates and normalized metrics derived from core post metrics."""

    model_config = ConfigDict(extra="forbid")

    engagement_rate: float | None = Field(
        default=None,
        description="Derived engagement rate for the post.",
    )
    save_rate: float | None = Field(
        default=None,
        description="Save rate relative to reach or views, depending on media type.",
    )
    share_rate: float | None = Field(
        default=None,
        description="Share rate relative to reach or views, depending on media type.",
    )
    watch_through_rate: float | None = Field(
        default=None,
        description="Watch-through/completion rate for video or reel content.",
    )
    swipe_through_rate: float | None = Field(
        default=None,
        description="Swipe-through rate for carousel or story-like content.",
    )
    like_rate: float | None = Field(default=None, description="Like rate for relative performance analysis.")
    comment_rate: float | None = Field(default=None, description="Comment rate for relative performance analysis.")
    save_to_share_ratio: float | None = Field(
        default=None,
        description="Ratio of saves to shares as a content-intent signal.",
    )
    profile_visit_rate: float | None = Field(
        default=None,
        description="Rate of profile visits generated by the post.",
    )
    website_tap_rate: float | None = Field(
        default=None,
        description="Rate of website taps generated by the post.",
    )
    reach_to_impression_ratio: float | None = Field(
        default=None,
        description="Reach divided by impressions to indicate repeat exposure density.",
    )
    engagements_total: int | None = Field(
        default=None,
        description="Total engagement actions (likes + comments + saves + shares).",
    )


# -----------------------------
# Benchmark metrics
# -----------------------------


class BenchmarkMetrics(BaseModel):
    """Account-level benchmark values and percent-vs-average comparisons."""

    model_config = ConfigDict(extra="forbid")

    account_avg_reach: float | None = Field(
        default=None,
        description="Account-level average reach used as benchmark.",
    )
    account_avg_engagement_rate: float | None = Field(
        default=None,
        description="Account-level average engagement rate used as benchmark.",
    )
    percentile_engagement_rank: float | None = Field(
        default=None,
        description="Percentile rank for this post's engagement against account history.",
    )
    reach_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of post reach compared to account average reach.",
    )
    engagement_rate_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of engagement rate compared to account average.",
    )
    impressions_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of impressions compared to account average.",
    )
    likes_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of likes compared to account average.",
    )
    comments_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of comments compared to account average.",
    )
    shares_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of shares compared to account average.",
    )
    saves_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of saves compared to account average.",
    )
    profile_visits_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of profile visits compared to account average.",
    )
    website_taps_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of website taps compared to account average.",
    )


class VisionSignal(BaseModel):
    """Normalized Gemini vision signal payload for a single post."""

    model_config = ConfigDict(extra="forbid")

    objects: list[str] = Field(
        default_factory=list,
        description="Detected objects in the post media.",
    )
    scene_description: str | None = Field(
        default=None,
        description="Free-text scene description from vision analysis.",
    )
    detected_text: str | None = Field(
        default=None,
        description="OCR text detected in the media, if any.",
    )
    visual_style: str | None = Field(
        default=None,
        description="Visual style descriptor inferred by vision model.",
    )
    hook_strength_score: float | None = Field(
        default=None,
        description="Vision-estimated hook strength in range 0..1.",
    )
    primary_objects: list[str] | None = Field(
        default=None,
        description="Primary objects used for deterministic visual scoring.",
    )
    dominant_focus: str | None = Field(
        default=None,
        description="Dominant visual focus entity.",
    )
    dominant_object: str | None = Field(
        default=None,
        description="Alias for dominant focus entity when provided.",
    )
    scene_type: str | None = Field(
        default=None,
        description="Scene category label, if available.",
    )
    lighting_quality: float | str | None = Field(
        default=None,
        description="Optional lighting quality signal as numeric or categorical value.",
    )
    subject_clarity: float | str | None = Field(
        default=None,
        description="Optional subject clarity signal as numeric or categorical value.",
    )
    aesthetic_quality: float | str | None = Field(
        default=None,
        description="Optional aesthetic quality signal as numeric or categorical value.",
    )

    @field_validator("hook_strength_score", mode="before")
    @classmethod
    def _clamp_hook_strength(cls, value: float | int | str | None) -> float | None:
        if value is None:
            return None
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return None
        return max(0.0, min(1.0, numeric))


class VisionAnalysis(BaseModel):
    """Container for vision provider output."""

    model_config = ConfigDict(extra="forbid")

    provider: str = Field(default="gemini", description="Vision provider identifier.")
    status: str = Field(default="error", description="Vision analysis status.")
    signals: list[VisionSignal] = Field(default_factory=list, description="Normalized vision signal payloads.")


class VisualQualityScore(BaseModel):
    """Deterministic S1 visual quality score and sub-scores."""

    model_config = ConfigDict(extra="forbid")

    composition: float = Field(default=0.0, ge=0.0, le=10.0)
    lighting: float = Field(default=0.0, ge=0.0, le=10.0)
    subject_clarity: float = Field(default=0.0, ge=0.0, le=10.0)
    aesthetic_quality: float = Field(default=0.0, ge=0.0, le=10.0)
    total: float = Field(default=0.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator("composition", "lighting", "subject_clarity", "aesthetic_quality", mode="before")
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(10.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:120])
        return sanitized


class ContentClarityScore(BaseModel):
    """Deterministic S3 content clarity score and sub-scores."""

    model_config = ConfigDict(extra="forbid")

    message_singularity: float = Field(default=0.0, ge=0.0, le=10.0)
    context_clarity: float = Field(default=0.0, ge=0.0, le=10.0)
    caption_alignment: float = Field(default=0.0, ge=0.0, le=10.0)
    visual_message_support: float = Field(default=0.0, ge=0.0, le=10.0)
    cognitive_load: float = Field(default=0.0, ge=0.0, le=10.0)
    total: float = Field(default=0.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator(
        "message_singularity",
        "context_clarity",
        "caption_alignment",
        "visual_message_support",
        "cognitive_load",
        mode="before",
    )
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(10.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:120])
        return sanitized


class EngagementPotentialScore(BaseModel):
    """AI-derived S5 engagement potential score and sub-scores."""

    model_config = ConfigDict(extra="forbid")

    emotional_resonance: float = Field(default=0.0, ge=0.0, le=10.0)
    shareability: float = Field(default=0.0, ge=0.0, le=10.0)
    save_worthiness: float = Field(default=0.0, ge=0.0, le=10.0)
    comment_potential: float = Field(default=0.0, ge=0.0, le=10.0)
    novelty_or_value: float = Field(default=0.0, ge=0.0, le=10.0)
    total: float = Field(default=0.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator(
        "emotional_resonance",
        "shareability",
        "save_worthiness",
        "comment_potential",
        "novelty_or_value",
        mode="before",
    )
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(10.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:120])
        return sanitized


class WeightedPostScore(BaseModel):
    """Spec-aligned weighted post score P across available sub-scores."""

    model_config = ConfigDict(extra="forbid")

    post_type: str = Field(default="IMAGE")
    # User-facing aggregate is 0..100 while we keep normalized 0..50 for transparency.
    score: float = Field(default=50.0, ge=0.0, le=100.0)
    normalized_score_0_50: float = Field(default=25.0, ge=0.0, le=50.0)
    components: dict[str, float | None] = Field(default_factory=dict)
    weights_used: dict[str, float] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)

    @field_validator("score", mode="before")
    @classmethod
    def _clamp_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 50.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 50.0
        return round(max(0.0, min(100.0, numeric)), 2)

    @field_validator("normalized_score_0_50", mode="before")
    @classmethod
    def _clamp_normalized_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 25.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 25.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("components", mode="before")
    @classmethod
    def _sanitize_components(cls, value: dict[str, float | int | str | None] | None) -> dict[str, float | None]:
        if not isinstance(value, dict):
            return {}
        sanitized: dict[str, float | None] = {}
        for key, raw in value.items():
            if not isinstance(key, str):
                continue
            if raw is None:
                sanitized[key] = None
                continue
            try:
                numeric = float(raw)
            except (TypeError, ValueError):
                sanitized[key] = None
                continue
            sanitized[key] = round(max(0.0, min(50.0, numeric)), 2)
        return sanitized

    @field_validator("weights_used", mode="before")
    @classmethod
    def _sanitize_weights_used(cls, value: dict[str, float | int | str] | None) -> dict[str, float]:
        if not isinstance(value, dict):
            return {}
        sanitized: dict[str, float] = {}
        for key, raw in value.items():
            if not isinstance(key, str):
                continue
            try:
                numeric = float(raw)
            except (TypeError, ValueError):
                continue
            sanitized[key] = round(max(0.0, numeric), 6)
        return sanitized

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class CaptionEffectivenessScore(BaseModel):
    """Deterministic S2 caption effectiveness score."""

    model_config = ConfigDict(extra="forbid")

    hook_score_0_100: int = Field(default=30, ge=0, le=100)
    length_score_0_100: int = Field(default=30, ge=0, le=100)
    hashtag_score_0_100: int = Field(default=20, ge=0, le=100)
    cta_score_0_100: int = Field(default=20, ge=0, le=100)
    s2_raw_0_100: int = Field(default=25, ge=0, le=100)
    total_0_50: float = Field(default=12.5, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator(
        "hook_score_0_100",
        "length_score_0_100",
        "hashtag_score_0_100",
        "cta_score_0_100",
        "s2_raw_0_100",
        mode="before",
    )
    @classmethod
    def _clamp_int_0_100(cls, value: int | float | str | None, info: ValidationInfo) -> int:
        field_default = cls.model_fields[info.field_name].default
        if value is None:
            return int(field_default)
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("total_0_50", mode="before")
    @classmethod
    def _clamp_total_0_50(cls, value: int | float | str | None, info: ValidationInfo) -> float:
        field_default = cls.model_fields[info.field_name].default
        if value is None:
            return float(field_default)
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 1)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class AudienceRelevanceScore(BaseModel):
    """Deterministic S4 audience relevance score."""

    model_config = ConfigDict(extra="forbid")

    post_category: str | None = Field(default=None)
    creator_dominant_category: str | None = Field(default=None)
    affinity_band: Literal["EXACT", "ADJACENT", "UNRELATED", "UNKNOWN"] = Field(default="UNKNOWN")
    s4_raw_0_100: int = Field(default=50, ge=0, le=100)
    total_0_50: float = Field(default=25.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator("s4_raw_0_100", mode="before")
    @classmethod
    def _clamp_s4_raw(cls, value: int | float | str | None) -> int:
        if value is None:
            return 50
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 50
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("total_0_50", mode="before")
    @classmethod
    def _clamp_total_0_50(cls, value: int | float | str | None) -> float:
        if value is None:
            return 25.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 25.0
        return round(max(0.0, min(50.0, numeric)), 1)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class BrandSafetyPenalty(BaseModel):
    """Structured S6 penalty entry."""

    model_config = ConfigDict(extra="forbid")

    key: str
    penalty: int = Field(ge=0, le=100)
    reason: str

    @field_validator("key", "reason", mode="before")
    @classmethod
    def _sanitize_text(cls, value: str | None) -> str:
        text = value if isinstance(value, str) else ""
        return text.strip()[:160]

    @field_validator("key")
    @classmethod
    def _validate_key_not_empty(cls, value: str) -> str:
        if value.strip() == "":
            raise ValueError("key must not be empty")
        return value

    @field_validator("reason")
    @classmethod
    def _validate_reason_not_empty(cls, value: str) -> str:
        if value.strip() == "":
            raise ValueError("reason must not be empty")
        return value

    @field_validator("penalty", mode="before")
    @classmethod
    def _clamp_penalty(cls, value: int | float | str | None) -> int:
        if value is None:
            return 0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0
        return int(max(0.0, min(100.0, round(numeric))))


class BrandSafetyScore(BaseModel):
    """Deterministic S6 brand safety score."""

    model_config = ConfigDict(extra="forbid")

    s6_raw_0_100: int = Field(default=100, ge=0, le=100)
    total_0_50: float = Field(default=50.0, ge=0.0, le=50.0)
    penalties: list[BrandSafetyPenalty] = Field(default_factory=list)
    flags: dict[str, bool] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)

    @field_validator("s6_raw_0_100", mode="before")
    @classmethod
    def _clamp_s6_raw(cls, value: int | float | str | None) -> int:
        if value is None:
            return 100
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 100
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("total_0_50", mode="before")
    @classmethod
    def _clamp_total_0_50(cls, value: int | float | str | None) -> float:
        if value is None:
            return 50.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 50.0
        return round(max(0.0, min(50.0, numeric)), 1)

    @field_validator("flags", mode="before")
    @classmethod
    def _sanitize_flags(cls, value: dict[str, bool] | None) -> dict[str, bool]:
        if not isinstance(value, dict):
            return {}
        sanitized: dict[str, bool] = {}
        for key, raw in value.items():
            if not isinstance(key, str):
                continue
            sanitized[key] = bool(raw)
        return sanitized

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class SinglePostInsights(BaseModel):
    """Canonical representation for Single Post Insights in the domain layer."""

    model_config = ConfigDict(extra="forbid")

    account_id: str | None = Field(default=None, description="Internal account identifier.")
    media_id: str | None = Field(default=None, description="Platform media identifier for the post.")
    media_url: str | None = Field(default=None, description="Public or signed media URL for vision analysis.")
    media_type: str | None = Field(default=None, description="Instagram media type (e.g., IMAGE, VIDEO, CAROUSEL).")
    caption_text: str = Field(default="", description="Post caption text used for deterministic clarity scoring.")
    post_category: str | None = Field(default=None, description="Predicted/assigned post category for audience relevance.")
    creator_dominant_category: str | None = Field(default=None, description="Creator dominant category for audience relevance.")
    extracted_brand_mentions: list[str] = Field(default_factory=list, description="Brand mentions extracted from post/caption.")
    safety_extra_flags: dict[str, bool] = Field(
        default_factory=dict,
        description="Optional upstream safety flags for deterministic S6 composition.",
    )
    follower_count: int | None = Field(default=None, description="Account followers at publish or snapshot time.")
    published_at: datetime | None = Field(default=None, description="Timestamp when the post was published.")
    core_metrics: CoreMetrics = Field(description="Raw post-level metrics.")
    derived_metrics: DerivedMetrics = Field(description="Calculated post-level derived metrics.")
    benchmark_metrics: BenchmarkMetrics = Field(description="Benchmark and percent-vs-average metrics.")
    vision_analysis: VisionAnalysis | None = Field(
        default=None,
        description="Latest normalized vision analysis payload for this post.",
    )
    visual_quality_score: VisualQualityScore = Field(
        default_factory=VisualQualityScore,
        description="Deterministic S1 visual quality score derived from vision signals.",
    )
    content_clarity_score: ContentClarityScore = Field(
        default_factory=ContentClarityScore,
        description="Deterministic S3 content clarity score derived from vision and caption.",
    )
    engagement_potential_score: EngagementPotentialScore = Field(
        default_factory=EngagementPotentialScore,
        description="AI-derived S5 engagement potential score with deterministic guardrails.",
    )
    caption_effectiveness_score: CaptionEffectivenessScore = Field(
        default_factory=CaptionEffectivenessScore,
        description="Deterministic S2 caption effectiveness score (raw 0..100 and mapped 0..50).",
    )
    audience_relevance_score: AudienceRelevanceScore = Field(
        default_factory=AudienceRelevanceScore,
        description="Deterministic S4 audience relevance score (raw 0..100 and mapped 0..50).",
    )
    brand_safety_score: BrandSafetyScore = Field(
        default_factory=BrandSafetyScore,
        description="Deterministic S6 brand safety score (raw 0..100 and mapped 0..50).",
    )
    weighted_post_score: WeightedPostScore = Field(
        default_factory=WeightedPostScore,
        description="Spec-aligned weighted post score P (0..100) with normalized 0..50 transparency field.",
    )
    tier_avg_engagement_rate: float | None = Field(
        default=None,
        description="Tier-level average engagement rate used for prediction (same unit as engagement_rate).",
    )
    predicted_engagement_rate: float | None = Field(
        default=None,
        description="Predicted engagement rate computed as tier_avg_engagement_rate * (S5.total / 50).",
    )
    predicted_engagement_rate_notes: list[str] = Field(
        default_factory=list,
        description="Deterministic notes explaining missing values, caps, and source selection for predicted ER.",
    )

    @field_validator("predicted_engagement_rate_notes", mode="before")
    @classmethod
    def _sanitize_predicted_engagement_rate_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized
