"""Canonical domain models for Single Post Insights."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator, model_validator


CRINGE_DETECTION_THRESHOLD = 45
CRINGE_NOT_CRINGE_MAX = 30
CRINGE_UNCERTAIN_MAX = 59


# -----------------------------
# Core metrics
# -----------------------------


class CoreMetrics(BaseModel):
    """Raw Instagram metrics captured from the source system for a single post."""

    model_config = ConfigDict(extra="forbid")

    reach: int | None = Field(default=None, description="Unique accounts reached by the post.")
    impressions: int | None = Field(default=None, description="Total impressions generated by the post.")
    likes: int | None = Field(default=None, description="Total likes on the post.")
    comments: int | None = Field(default=None, description="Total comments on the post.")
    shares: int | None = Field(default=None, description="Total shares of the post.")
    saves: int | None = Field(default=None, description="Total saves/bookmarks on the post.")
    profile_visits: int | None = Field(default=None, description="Profile visits attributed to the post.")
    website_taps: int | None = Field(default=None, description="Website taps attributed to the post.")
    source_engagement_rate: float | None = Field(
        default=None,
        description="Top-level raw engagement rate provided by source systems.",
    )


# -----------------------------
# Derived metrics
# -----------------------------


class DerivedMetrics(BaseModel):
    """Deterministic rates and normalized metrics derived from core post metrics."""

    model_config = ConfigDict(extra="forbid")

    engagement_rate: float | None = Field(
        default=None,
        description="Derived engagement rate for the post.",
    )
    save_rate: float | None = Field(
        default=None,
        description="Save rate relative to reach or views, depending on media type.",
    )
    share_rate: float | None = Field(
        default=None,
        description="Share rate relative to reach or views, depending on media type.",
    )
    watch_through_rate: float | None = Field(
        default=None,
        description="Watch-through/completion rate for video or reel content.",
    )
    swipe_through_rate: float | None = Field(
        default=None,
        description="Swipe-through rate for carousel or story-like content.",
    )
    like_rate: float | None = Field(default=None, description="Like rate for relative performance analysis.")
    comment_rate: float | None = Field(default=None, description="Comment rate for relative performance analysis.")
    save_to_share_ratio: float | None = Field(
        default=None,
        description="Ratio of saves to shares as a content-intent signal.",
    )
    profile_visit_rate: float | None = Field(
        default=None,
        description="Rate of profile visits generated by the post.",
    )
    website_tap_rate: float | None = Field(
        default=None,
        description="Rate of website taps generated by the post.",
    )
    reach_to_impression_ratio: float | None = Field(
        default=None,
        description="Reach divided by impressions to indicate repeat exposure density.",
    )
    engagements_total: int | None = Field(
        default=None,
        description="Total engagement actions (likes + comments + saves + shares).",
    )


# -----------------------------
# Benchmark metrics
# -----------------------------


class BenchmarkMetrics(BaseModel):
    """Account-level benchmark values and percent-vs-average comparisons."""

    model_config = ConfigDict(extra="forbid")

    account_avg_reach: float | None = Field(
        default=None,
        description="Account-level average reach used as benchmark.",
    )
    account_avg_engagement_rate: float | None = Field(
        default=None,
        description="Account-level average engagement rate used as benchmark.",
    )
    percentile_engagement_rank: float | None = Field(
        default=None,
        description="Percentile rank for this post's engagement against account history.",
    )
    reach_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of post reach compared to account average reach.",
    )
    engagement_rate_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of engagement rate compared to account average.",
    )
    impressions_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of impressions compared to account average.",
    )
    likes_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of likes compared to account average.",
    )
    comments_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of comments compared to account average.",
    )
    shares_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of shares compared to account average.",
    )
    saves_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of saves compared to account average.",
    )
    profile_visits_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of profile visits compared to account average.",
    )
    website_taps_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of website taps compared to account average.",
    )


class VisionSignal(BaseModel):
    """Normalized Gemini vision signal payload for a single post."""

    model_config = ConfigDict(extra="forbid")

    objects: list[str] = Field(
        default_factory=list,
        description="Detected objects in the post media.",
    )
    scene_description: str | None = Field(
        default=None,
        description="Free-text scene description from vision analysis.",
    )
    detected_text: str | None = Field(
        default=None,
        description="OCR text detected in the media, if any.",
    )
    visual_style: str | None = Field(
        default=None,
        description="Visual style descriptor inferred by vision model.",
    )
    visual_quality_score: dict[str, float] | None = Field(
        default=None,
        description="Optional raw S1 visual quality sub-scores from vision model.",
    )
    technical_flaws: list[str] = Field(
        default_factory=list,
        description="Optional list of technical flaws detected by vision model.",
    )
    hook_strength_score: float | None = Field(
        default=None,
        description="Vision-estimated hook strength in range 0..1.",
    )
    primary_objects: list[str] | None = Field(
        default=None,
        description="Primary objects used for deterministic visual scoring.",
    )
    dominant_focus: str | None = Field(
        default=None,
        description="Dominant visual focus entity.",
    )
    dominant_object: str | None = Field(
        default=None,
        description="Alias for dominant focus entity when provided.",
    )
    scene_type: str | None = Field(
        default=None,
        description="Scene category label, if available.",
    )
    lighting_quality: float | str | None = Field(
        default=None,
        description="Optional lighting quality signal as numeric or categorical value.",
    )
    subject_clarity: float | str | None = Field(
        default=None,
        description="Optional subject clarity signal as numeric or categorical value.",
    )
    aesthetic_quality: float | str | None = Field(
        default=None,
        description="Optional aesthetic quality signal as numeric or categorical value.",
    )
    cringe_score: int | None = Field(
        default=None,
        ge=0,
        le=100,
        description="Visual cringe score 0-100.",
    )
    cringe_signals: list[str] = Field(
        default_factory=list,
        description="Visual cringe signals detected.",
    )
    cringe_fixes: list[str] = Field(
        default_factory=list,
        description="Suggested fixes to reduce cringe.",
    )
    production_level: str | None = Field(
        default=None,
        description="low|medium|high production level.",
    )
    is_cringe: bool | None = Field(
        default=None,
        description=(
            "True when cringe risk is detected (score >= 45). "
            "This can be true while cringe_label is 'uncertain' for scores 45-59."
        ),
    )
    cringe_label: str | None = Field(
        default=None,
        description="not_cringe|uncertain|cringe label.",
    )
    adult_content_detected: bool | None = Field(default=None)
    adult_content_confidence: int | None = Field(default=None, ge=0, le=100)

    @field_validator("hook_strength_score", mode="before")
    @classmethod
    def _clamp_hook_strength(cls, value: float | int | str | None) -> float | None:
        if value is None:
            return None
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return None
        return max(0.0, min(1.0, numeric))

    @field_validator("cringe_score", "adult_content_confidence", mode="before")
    @classmethod
    def _clamp_percent_score(cls, value: int | float | str | None) -> int | None:
        if value is None:
            return None
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return None
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("cringe_signals", "cringe_fixes", mode="before")
    @classmethod
    def _sanitize_cringe_list(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
            if len(sanitized) == 3:
                break
        return sanitized

    @field_validator("technical_flaws", mode="before")
    @classmethod
    def _sanitize_technical_flaws(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
            if len(sanitized) >= 3:
                break
        return sanitized

    @field_validator("production_level", mode="before")
    @classmethod
    def _normalize_production_level(cls, value: str | None) -> str | None:
        if not isinstance(value, str):
            return None
        text = value.strip().lower()
        if text not in {"low", "medium", "high"}:
            return None
        return text

    @field_validator("is_cringe", "adult_content_detected", mode="before")
    @classmethod
    def _normalize_bool(cls, value: bool | int | float | str | None) -> bool | None:
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return bool(value)
        if isinstance(value, str):
            text = value.strip().lower()
            if text in {"1", "true", "yes", "y"}:
                return True
            if text in {"0", "false", "no", "n"}:
                return False
        return None

    @field_validator("cringe_label", mode="before")
    @classmethod
    def _sanitize_cringe_label(cls, value: str | None) -> str | None:
        if not isinstance(value, str):
            return None
        text = value.strip().lower()
        return text if text in {"not_cringe", "uncertain", "cringe"} else None

    @staticmethod
    def _derive_label_from_score(score: int | None) -> str | None:
        if score is None:
            return None
        if score <= CRINGE_NOT_CRINGE_MAX:
            return "not_cringe"
        if score <= CRINGE_UNCERTAIN_MAX:
            return "uncertain"
        return "cringe"

    @model_validator(mode="after")
    def _derive_cringe_fields(self) -> "VisionSignal":
        derived_label = self._derive_label_from_score(self.cringe_score)
        if derived_label is not None:
            self.cringe_label = derived_label
            # Intentional semantic split:
            # - is_cringe: safety-risk detection threshold (>=45)
            # - cringe_label: severity bucket ("cringe" only at >=60)
            self.is_cringe = (
                self.cringe_score >= CRINGE_DETECTION_THRESHOLD
                if self.cringe_score is not None
                else None
            )
        return self


class VisionAnalysis(BaseModel):
    """Container for vision provider output."""

    model_config = ConfigDict(extra="forbid")

    provider: str = Field(default="gemini", description="Vision provider identifier.")
    status: Literal["ok", "error", "disabled", "no_media", "unknown"] = Field(
        default="unknown",
        description="Vision analysis status.",
    )
    signals: list[VisionSignal] = Field(default_factory=list, description="Normalized vision signal payloads.")


class ReelAnalysis(BaseModel):
    """Reel-specific scores only populated when media_type == REEL."""

    model_config = ConfigDict(extra="forbid")

    hook_score: float | None = Field(default=None, ge=0.0, le=50.0)
    pacing_score: float | None = Field(default=None, ge=0.0, le=50.0)
    audio_alignment_score: float | None = Field(default=None, ge=0.0, le=50.0)
    retention_score: float | None = Field(default=None, ge=0.0, le=50.0)
    total: float | None = Field(default=None, ge=0.0, le=100.0)
    reel_vision_status: str | None = Field(default=None, description="ok | error | disabled")
    notes: list[str] = Field(default_factory=list)

    @field_validator("hook_score", "pacing_score", "audio_alignment_score", "retention_score", mode="before")
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float | None:
        if value is None:
            return None
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return None
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float | None:
        if value is None:
            return None
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return None
        return round(max(0.0, min(100.0, numeric)), 2)

    @field_validator("reel_vision_status", mode="before")
    @classmethod
    def _normalize_reel_vision_status(cls, value: str | None) -> str | None:
        if not isinstance(value, str):
            return None
        text = value.strip().lower()
        if text not in {"ok", "error", "disabled"}:
            return None
        return text

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class VisualQualityScore(BaseModel):
    """Deterministic S1 visual quality score and sub-scores."""

    model_config = ConfigDict(extra="forbid")

    composition: float = Field(default=0.0, ge=0.0, le=10.0)
    lighting: float = Field(default=0.0, ge=0.0, le=10.0)
    subject_clarity: float = Field(default=0.0, ge=0.0, le=10.0)
    aesthetic_quality: float = Field(default=0.0, ge=0.0, le=10.0)
    total: float = Field(default=0.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator("composition", "lighting", "subject_clarity", "aesthetic_quality", mode="before")
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(10.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:120])
        return sanitized


class ContentClarityScore(BaseModel):
    """Deterministic S3 content clarity score and sub-scores."""

    model_config = ConfigDict(extra="forbid")

    message_singularity: float = Field(default=0.0, ge=0.0, le=10.0)
    context_clarity: float = Field(default=0.0, ge=0.0, le=10.0)
    caption_alignment: float = Field(default=0.0, ge=0.0, le=10.0)
    visual_message_support: float = Field(default=0.0, ge=0.0, le=10.0)
    cognitive_load: float = Field(default=0.0, ge=0.0, le=10.0)
    total: float = Field(default=0.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator(
        "message_singularity",
        "context_clarity",
        "caption_alignment",
        "visual_message_support",
        "cognitive_load",
        mode="before",
    )
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(10.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:120])
        return sanitized


class EngagementPotentialScore(BaseModel):
    """AI-derived S5 engagement potential score and sub-scores."""

    model_config = ConfigDict(extra="forbid")

    emotional_resonance: float = Field(default=0.0, ge=0.0, le=10.0)
    shareability: float = Field(default=0.0, ge=0.0, le=10.0)
    save_worthiness: float = Field(default=0.0, ge=0.0, le=10.0)
    comment_potential: float = Field(default=0.0, ge=0.0, le=10.0)
    novelty_or_value: float = Field(default=0.0, ge=0.0, le=10.0)
    total: float = Field(default=0.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator(
        "emotional_resonance",
        "shareability",
        "save_worthiness",
        "comment_potential",
        "novelty_or_value",
        mode="before",
    )
    @classmethod
    def _clamp_sub_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(10.0, numeric)), 2)

    @field_validator("total", mode="before")
    @classmethod
    def _clamp_total(cls, value: float | int | str | None) -> float:
        if value is None:
            return 0.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:120])
        return sanitized


class WeightedPostScore(BaseModel):
    """Spec-aligned weighted post score P across available sub-scores."""

    model_config = ConfigDict(extra="forbid")

    post_type: str = Field(default="IMAGE")
    # User-facing aggregate is 0..100 while we keep normalized 0..50 for transparency.
    score: float = Field(default=50.0, ge=0.0, le=100.0)
    normalized_score_0_50: float = Field(default=25.0, ge=0.0, le=50.0)
    components: dict[str, float | None] = Field(default_factory=dict)
    weights_used: dict[str, float] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)

    @field_validator("score", mode="before")
    @classmethod
    def _clamp_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 50.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 50.0
        return round(max(0.0, min(100.0, numeric)), 2)

    @field_validator("normalized_score_0_50", mode="before")
    @classmethod
    def _clamp_normalized_score(cls, value: float | int | str | None) -> float:
        if value is None:
            return 25.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 25.0
        return round(max(0.0, min(50.0, numeric)), 2)

    @field_validator("components", mode="before")
    @classmethod
    def _sanitize_components(cls, value: dict[str, float | int | str | None] | None) -> dict[str, float | None]:
        if not isinstance(value, dict):
            return {}
        sanitized: dict[str, float | None] = {}
        for key, raw in value.items():
            if not isinstance(key, str):
                continue
            if raw is None:
                sanitized[key] = None
                continue
            try:
                numeric = float(raw)
            except (TypeError, ValueError):
                sanitized[key] = None
                continue
            sanitized[key] = round(max(0.0, min(50.0, numeric)), 2)
        return sanitized

    @field_validator("weights_used", mode="before")
    @classmethod
    def _sanitize_weights_used(cls, value: dict[str, float | int | str] | None) -> dict[str, float]:
        if not isinstance(value, dict):
            return {}
        sanitized: dict[str, float] = {}
        for key, raw in value.items():
            if not isinstance(key, str):
                continue
            try:
                numeric = float(raw)
            except (TypeError, ValueError):
                continue
            sanitized[key] = round(max(0.0, numeric), 6)
        return sanitized

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class CaptionEffectivenessScore(BaseModel):
    """Deterministic S2 caption effectiveness score."""

    model_config = ConfigDict(extra="forbid")

    hook_score_0_100: int = Field(default=30, ge=0, le=100)
    length_score_0_100: int = Field(default=30, ge=0, le=100)
    hashtag_score_0_100: int = Field(default=20, ge=0, le=100)
    cta_score_0_100: int = Field(default=20, ge=0, le=100)
    s2_raw_0_100: int = Field(default=25, ge=0, le=100)
    total_0_50: float = Field(default=12.5, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator(
        "hook_score_0_100",
        "length_score_0_100",
        "hashtag_score_0_100",
        "cta_score_0_100",
        "s2_raw_0_100",
        mode="before",
    )
    @classmethod
    def _clamp_int_0_100(cls, value: int | float | str | None, info: ValidationInfo) -> int:
        field_default = cls.model_fields[info.field_name].default
        if value is None:
            return int(field_default)
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return int(field_default)
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("total_0_50", mode="before")
    @classmethod
    def _clamp_total_0_50(cls, value: int | float | str | None, info: ValidationInfo) -> float:
        field_default = cls.model_fields[info.field_name].default
        if value is None:
            return float(field_default)
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return float(field_default)
        return round(max(0.0, min(50.0, numeric)), 1)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class AudienceRelevanceScore(BaseModel):
    """Deterministic S4 audience relevance score."""

    model_config = ConfigDict(extra="forbid")

    post_category: str | None = Field(default=None)
    creator_dominant_category: str | None = Field(default=None)
    affinity_band: Literal["EXACT", "HIGH_OVERLAP", "ADJACENT", "UNRELATED", "UNKNOWN"] = Field(
        default="UNKNOWN"
    )
    s4_raw_0_100: int = Field(default=50, ge=0, le=100)
    total_0_50: float = Field(default=25.0, ge=0.0, le=50.0)
    notes: list[str] = Field(default_factory=list)

    @field_validator("s4_raw_0_100", mode="before")
    @classmethod
    def _clamp_s4_raw(cls, value: int | float | str | None) -> int:
        if value is None:
            return 50
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 50
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("total_0_50", mode="before")
    @classmethod
    def _clamp_total_0_50(cls, value: int | float | str | None) -> float:
        if value is None:
            return 25.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 25.0
        return round(max(0.0, min(50.0, numeric)), 1)

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class BrandSafetyPenalty(BaseModel):
    """Structured S6 penalty entry."""

    model_config = ConfigDict(extra="forbid")

    key: str
    penalty: int = Field(ge=0, le=100)
    reason: str

    @field_validator("key", "reason", mode="before")
    @classmethod
    def _sanitize_text(cls, value: str | None) -> str:
        text = value if isinstance(value, str) else ""
        return text.strip()[:160]

    @field_validator("key")
    @classmethod
    def _validate_key_not_empty(cls, value: str) -> str:
        if value.strip() == "":
            raise ValueError("key must not be empty")
        return value

    @field_validator("reason")
    @classmethod
    def _validate_reason_not_empty(cls, value: str) -> str:
        if value.strip() == "":
            raise ValueError("reason must not be empty")
        return value

    @field_validator("penalty", mode="before")
    @classmethod
    def _clamp_penalty(cls, value: int | float | str | None) -> int:
        if value is None:
            return 0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 0
        return int(max(0.0, min(100.0, round(numeric))))


class BrandSafetyScore(BaseModel):
    """Deterministic S6 brand safety score."""

    model_config = ConfigDict(extra="forbid")

    s6_raw_0_100: int = Field(default=100, ge=0, le=100)
    total_0_50: float = Field(default=50.0, ge=0.0, le=50.0)
    penalties: list[BrandSafetyPenalty] = Field(default_factory=list)
    flags: dict[str, bool] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)

    @field_validator("s6_raw_0_100", mode="before")
    @classmethod
    def _clamp_s6_raw(cls, value: int | float | str | None) -> int:
        if value is None:
            return 100
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 100
        return int(max(0.0, min(100.0, round(numeric))))

    @field_validator("total_0_50", mode="before")
    @classmethod
    def _clamp_total_0_50(cls, value: int | float | str | None) -> float:
        if value is None:
            return 50.0
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return 50.0
        return round(max(0.0, min(50.0, numeric)), 1)

    @field_validator("flags", mode="before")
    @classmethod
    def _sanitize_flags(cls, value: dict[str, bool] | None) -> dict[str, bool]:
        if not isinstance(value, dict):
            return {}
        sanitized: dict[str, bool] = {}
        for key, raw in value.items():
            if not isinstance(key, str):
                continue
            sanitized[key] = bool(raw)
        return sanitized

    @field_validator("notes", mode="before")
    @classmethod
    def _sanitize_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized


class SinglePostInsights(BaseModel):
    """Canonical representation for Single Post Insights in the domain layer."""

    model_config = ConfigDict(extra="forbid")

    account_id: str | None = Field(default=None, description="Internal account identifier.")
    media_id: str | None = Field(default=None, description="Platform media identifier for the post.")
    media_url: str | None = Field(default=None, description="Public or signed media URL for vision analysis.")
    media_type: str | None = Field(default=None, description="Instagram media type (e.g., IMAGE, VIDEO, CAROUSEL).")
    caption_text: str = Field(default="", description="Post caption text used for deterministic clarity scoring.")
    post_category: str | None = Field(default=None, description="Predicted/assigned post category for audience relevance.")
    creator_dominant_category: str | None = Field(default=None, description="Creator dominant category for audience relevance.")
    extracted_brand_mentions: list[str] = Field(default_factory=list, description="Brand mentions extracted from post/caption.")
    safety_extra_flags: dict[str, bool] = Field(
        default_factory=dict,
        description="Optional upstream safety flags for deterministic S6 composition.",
    )
    follower_count: int | None = Field(default=None, description="Account followers at publish or snapshot time.")
    published_at: datetime | None = Field(default=None, description="Timestamp when the post was published.")
    core_metrics: CoreMetrics = Field(
        default_factory=CoreMetrics,
        description="Raw post-level metrics.",
    )
    derived_metrics: DerivedMetrics = Field(
        default_factory=DerivedMetrics,
        description="Calculated post-level derived metrics.",
    )
    benchmark_metrics: BenchmarkMetrics = Field(
        default_factory=BenchmarkMetrics,
        description="Benchmark and percent-vs-average metrics.",
    )
    vision_analysis: VisionAnalysis | None = Field(
        default=None,
        description="Latest normalized vision analysis payload for this post.",
    )
    reel_analysis: ReelAnalysis | None = Field(
        default=None,
        description="Reel-specific analysis payload when media_type is REEL.",
    )
    visual_quality_score: VisualQualityScore = Field(
        default_factory=VisualQualityScore,
        description="Deterministic S1 visual quality score derived from vision signals.",
    )
    content_clarity_score: ContentClarityScore = Field(
        default_factory=ContentClarityScore,
        description="Deterministic S3 content clarity score derived from vision and caption.",
    )
    engagement_potential_score: EngagementPotentialScore = Field(
        default_factory=EngagementPotentialScore,
        description="AI-derived S5 engagement potential score with deterministic guardrails.",
    )
    caption_effectiveness_score: CaptionEffectivenessScore = Field(
        default_factory=CaptionEffectivenessScore,
        description="Deterministic S2 caption effectiveness score (raw 0..100 and mapped 0..50).",
    )
    audience_relevance_score: AudienceRelevanceScore = Field(
        default_factory=AudienceRelevanceScore,
        description="Deterministic S4 audience relevance score (raw 0..100 and mapped 0..50).",
    )
    brand_safety_score: BrandSafetyScore = Field(
        default_factory=BrandSafetyScore,
        description="Deterministic S6 brand safety score (raw 0..100 and mapped 0..50).",
    )
    weighted_post_score: WeightedPostScore = Field(
        default_factory=WeightedPostScore,
        description="Spec-aligned weighted post score P (0..100) with normalized 0..50 transparency field.",
    )
    tier_avg_engagement_rate: float | None = Field(
        default=None,
        description="Tier-level average engagement rate used for prediction (same unit as engagement_rate).",
    )
    predicted_engagement_rate: float | None = Field(
        default=None,
        description="Predicted engagement rate computed as tier_avg_engagement_rate * (S5.total / 50).",
    )
    predicted_engagement_rate_notes: list[str] = Field(
        default_factory=list,
        description="Deterministic notes explaining missing values, caps, and source selection for predicted ER.",
    )

    @field_validator("predicted_engagement_rate_notes", mode="before")
    @classmethod
    def _sanitize_predicted_engagement_rate_notes(cls, value: list[str] | str | None) -> list[str]:
        if value is None:
            return []
        values = value if isinstance(value, list) else [value]
        sanitized: list[str] = []
        for item in values:
            if not isinstance(item, str):
                continue
            text = item.strip()
            if not text:
                continue
            sanitized.append(text[:160])
        return sanitized
