"""Canonical domain models for Single Post Insights."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


# -----------------------------
# Core metrics
# -----------------------------


class CoreMetrics(BaseModel):
    """Raw Instagram metrics captured from the source system for a single post."""

    model_config = ConfigDict(extra="forbid")

    reach: int | None = Field(default=None, description="Unique accounts reached by the post.")
    impressions: int | None = Field(default=None, description="Total impressions generated by the post.")
    likes: int | None = Field(default=None, description="Total likes on the post.")
    comments: int | None = Field(default=None, description="Total comments on the post.")
    shares: int | None = Field(default=None, description="Total shares of the post.")
    saves: int | None = Field(default=None, description="Total saves/bookmarks on the post.")
    profile_visits: int | None = Field(default=None, description="Profile visits attributed to the post.")
    website_taps: int | None = Field(default=None, description="Website taps attributed to the post.")
    source_engagement_rate: float | None = Field(
        default=None,
        description="Top-level raw engagement rate provided by source systems.",
    )


# -----------------------------
# Derived metrics
# -----------------------------


class DerivedMetrics(BaseModel):
    """Deterministic rates and normalized metrics derived from core post metrics."""

    model_config = ConfigDict(extra="forbid")

    engagement_rate: float | None = Field(
        default=None,
        description="Derived engagement rate for the post.",
    )
    save_rate: float | None = Field(
        default=None,
        description="Save rate relative to reach or views, depending on media type.",
    )
    share_rate: float | None = Field(
        default=None,
        description="Share rate relative to reach or views, depending on media type.",
    )
    watch_through_rate: float | None = Field(
        default=None,
        description="Watch-through/completion rate for video or reel content.",
    )
    swipe_through_rate: float | None = Field(
        default=None,
        description="Swipe-through rate for carousel or story-like content.",
    )
    like_rate: float | None = Field(default=None, description="Like rate for relative performance analysis.")
    comment_rate: float | None = Field(default=None, description="Comment rate for relative performance analysis.")
    save_to_share_ratio: float | None = Field(
        default=None,
        description="Ratio of saves to shares as a content-intent signal.",
    )
    profile_visit_rate: float | None = Field(
        default=None,
        description="Rate of profile visits generated by the post.",
    )
    website_tap_rate: float | None = Field(
        default=None,
        description="Rate of website taps generated by the post.",
    )
    reach_to_impression_ratio: float | None = Field(
        default=None,
        description="Reach divided by impressions to indicate repeat exposure density.",
    )
    engagements_total: int | None = Field(
        default=None,
        description="Total engagement actions (likes + comments + saves + shares).",
    )


# -----------------------------
# Benchmark metrics
# -----------------------------


class BenchmarkMetrics(BaseModel):
    """Account-level benchmark values and percent-vs-average comparisons."""

    model_config = ConfigDict(extra="forbid")

    account_avg_reach: float | None = Field(
        default=None,
        description="Account-level average reach used as benchmark.",
    )
    account_avg_engagement_rate: float | None = Field(
        default=None,
        description="Account-level average engagement rate used as benchmark.",
    )
    percentile_engagement_rank: float | None = Field(
        default=None,
        description="Percentile rank for this post's engagement against account history.",
    )
    reach_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of post reach compared to account average reach.",
    )
    engagement_rate_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of engagement rate compared to account average.",
    )
    impressions_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of impressions compared to account average.",
    )
    likes_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of likes compared to account average.",
    )
    comments_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of comments compared to account average.",
    )
    shares_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of shares compared to account average.",
    )
    saves_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of saves compared to account average.",
    )
    profile_visits_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of profile visits compared to account average.",
    )
    website_taps_percent_vs_avg: float | None = Field(
        default=None,
        description="Percent difference of website taps compared to account average.",
    )


class SinglePostInsights(BaseModel):
    """Canonical representation for Single Post Insights in the domain layer."""

    model_config = ConfigDict(extra="forbid")

    account_id: str | None = Field(default=None, description="Internal account identifier.")
    media_id: str | None = Field(default=None, description="Platform media identifier for the post.")
    media_type: str | None = Field(default=None, description="Instagram media type (e.g., IMAGE, VIDEO, CAROUSEL).")
    published_at: datetime | None = Field(default=None, description="Timestamp when the post was published.")
    core_metrics: CoreMetrics = Field(description="Raw post-level metrics.")
    derived_metrics: DerivedMetrics = Field(description="Calculated post-level derived metrics.")
    benchmark_metrics: BenchmarkMetrics = Field(description="Benchmark and percent-vs-average metrics.")
